// import Head from 'next/head'
// import Image from 'next/image'
import Layout from "../../layouts/landing";
import Hero from "../../components/contact-us/hero";
import DownloadApp from "../../components/contact-us/downloadApp";
import ContactForm from "../../components/contact-us/contactForm";

export default function Faq() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Hero />
      <ContactForm />
      <DownloadApp />
    </>
  );
}

Faq.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
