// import Head from 'next/head'
// import Image from 'next/image'
import Layout from "../../layouts/landing";
import Hero from "../../components/faq/hero";
import DownloadApp from "../../components/faq/downloadApp";
import Accordion from "../../components/faq/accordion";
import Figures from "../../components/faq/figures";
import CurateArticle from "../../components/faq/curateArticle";

export default function Faq() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Hero />
      <Accordion />
      <DownloadApp />
      <Figures />
      <CurateArticle />
    </>
  );
}

Faq.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
