// import Head from 'next/head'
// import Image from 'next/image'
import Layout from "../../layouts/landing";
import Hero from "../../components/faq/hero";
// import CrowdFunding from "../../components/home/crowdFunding";
// import SafeInvesting from "../../components/home/safeInvesting";
// import HowWorks from "../../components/home/howWorks";
import DownloadApp from "../../components/faq/downloadApp";
import Accordion from "../../components/faq/accordion";
// import TrustedBy from "../../components/home/trustedBy";
// import WideOption from "../../components/home/wideOption";

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Hero />
      <Accordion />
      {/* <CrowdFunding />
      <SafeInvesting />
      <HowWorks /> */}
      <DownloadApp />
      {/* <TrustedBy />
      <WideOption /> */}
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
