// import Head from 'next/head'
// import Image from 'next/image'
import Layout from "../../layouts/landing";
import Hero from "../../components/aboutUs/hero";
import TrustedBy from "../../components/aboutUs/trustedBy";
import Figures from "../../components/aboutUs/figures";
import MissionVision from "../../components/aboutUs/missionVision";
import CrowdFunding from "../../components/aboutUs/crowdFunding";
import CrowdInvest from "../../components/aboutUs/crowdInvest";
import Team from "../../components/aboutUs/team";


export default function About() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Hero />
      <MissionVision />
      <CrowdInvest />
      <Team />
      <TrustedBy />
      <Figures />
      <CrowdFunding />
    </>
  );
}

About.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
