// import Head from 'next/head'
// import Image from 'next/image'
import Layout from "../../layouts/landing";
import Hero from "../../components/about-us/hero";
import TrustedBy from "../../components/about-us/trustedBy";
import Figures from "../../components/about-us/figures";
import MissionVision from "../../components/about-us/missionVision";
import CrowdFunding from "../../components/about-us/crowdFunding";
import CrowdInvest from "../../components/about-us/crowdInvest";
import Team from "../../components/about-us/team";
// import DownloadApp from "../../components/faq/downloadApp";
// import Accordion from "../../components/faq/accordion";
// import Figures from "../../components/faq/figures";
// import CurateArticle from "../../components/faq/curateArticle";

export default function About() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Hero />
      <MissionVision />
      <CrowdInvest />
      <Team />
      <TrustedBy />
      <Figures />
      <CrowdFunding />
    </>
  );
}

About.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
