// import Head from 'next/head'
// import Image from 'next/image'
import Layout from "../layouts/landing";
import HomeHero from "../components/home/hero";
import CrowdFunding from "../components/home/crowdFunding";
import SafeInvesting from "../components/home/safeInvesting";
import HowWorks from "../components/home/howWorks";
import DownloadApp from "../components/home/downloadApp";
import TrustedBy from "../components/home/trustedBy";

export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <HomeHero />
      <CrowdFunding />
      <SafeInvesting />
      <HowWorks />
      <DownloadApp />
      <TrustedBy />
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
