// import Head from 'next/head'
// import Image from 'next/image'
import Layout from "../layouts/landing";
import HomeHero from "../components/home/hero";
// import Companies from "../components/home/companies";
// import OurWork from "../components/home/ourWork";
// import WhyChooseUs from "../components/home/whyChooseUs";
// import Services from "../components/home/services";
// import WorkWith from "../components/home/workWith";
// import HomeContact from "../components/home/homeContact";
// import HomeInsight from "../components/home/homeInsight";
export default function Home() {
  return (
    <>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <HomeHero />
      {/* <Companies />
      <OurWork />
      <WhyChooseUs />
      <Services />
      <WorkWith heading="Working With Cloudfift" />
      <HomeContact />
      <HomeInsight /> */}
    </>
  );
}

Home.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};
